name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          app/package-lock.json
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install app dependencies
      run: cd app && npm ci --include=dev
    
    - name: Run type checking
      run: cd app && npm run typecheck
    
    - name: Run linting
      run: cd app && npm run lint
    
    - name: Run tests
      run: cd app && npm run test:ci
    
    - name: Build project
      run: cd app && npm run build
    
    - name: Test CLI installation
      run: |
        cd app
        npm install -g .
        scaffold-scripts --version