name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Primary testing on Ubuntu with multiple Node versions
          - os: ubuntu-latest
            node-version: 18
          - os: ubuntu-latest  
            node-version: 20
          # Cross-platform smoke tests on latest Node only
          - os: windows-latest
            node-version: 20
          - os: macos-latest
            node-version: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Test CLI commands (Unix)
        if: runner.os != 'Windows'
        run: |
          node dist/index.js --help
          node dist/index.js --version
          node dist/index.js list

      - name: Test CLI commands (Windows)
        if: runner.os == 'Windows'
        run: |
          node dist/index.js --help
          node dist/index.js --version
          node dist/index.js list